networks:
  sync:
    driver: bridge

services:
  web:
    image: ghcr.io/flamy-brave/brave-go-sync-server:master
    ports:
      - "8295:8295"
    depends_on:
      - dynamo-local
      - redis
    networks:
      - sync
    environment:
      - PPROF_ENABLED=true
      - SENTRY_DSN
      - ENV=local
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=GOSYNC
      - AWS_SECRET_ACCESS_KEY=GOSYNC
      - AWS_REGION=us-west-2
      - AWS_ENDPOINT=http://dynamo-local:8000
      - TABLE_NAME=client-entity-dev
      - REDIS_URL=redis:6379
  dynamo-local:
    image: ghcr.io/flamy-brave/brave-go-sync-dynamo:master
    ports:
      - "8000:8000"
    volumes:
      - ./dynamo-data:/db
    networks:
      - sync
  redis:
    # Change out the version number for "latest" if you don't want to update this file.
    image: public.ecr.aws/docker/library/redis:6.2
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - sync
